# Generated by Django 4.2.9 on 2024-02-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_about_post_profile_service_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='salary',
            field=models.IntegerField(default=100),
        ),
    ]
